version: '3.4'

services:
  blacksoil.blazor.server:
    image: blacksoilblazorserver
    build:
      context: ./BlackSoil.Blazor.Server
      dockerfile: Dockerfile

  blacksoil.aspnet:
    image: ${DOCKER_REGISTRY}blacksoilaspnet
    build:
      context: .
      dockerfile: BlackSoil.AspNet/Dockerfile

