apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
type: Opaque
stringData:
  oauth2_proxy.cfg: |
    http_address = ":4180"
    redirect_url = "https://azureaad-dnvgl.westeurope.cloudapp.azure.com/oauth2/callback"
    upstreams = "http://localhost:80/"
    request_logging = true
    authenticated_emails_file = "/authorization/oauth2_emails.cfg"
    client_id = "to be replaced"
    client_secret = "to be replaced"
    pass_basic_auth = false
    cookie_name = "kibana_sso_cookie"
    cookie_secret = "9adfb3026765c5bab7ec0d59c741f5bc"
    cookie_domain = "azureaad-dnvgl.westeurope.cloudapp.azure.com"
    cookie_expire = "168h0m"
    cookie_refresh = "60m"
    cookie_secure = true
    cookie_httponly = true
    provider="azure"
    skip_provider_button = true