apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "sqldb-pv"
  annotations:
    volume.beta.kubernetes.io/storage-class: "localstorageclass"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "4Gi"